hash-format = "sha256"

[[files]]
file = "mods/advanced-netherite.pw.toml"
hash = "0953ffeda5f045b69396bf318db0ddb9bf02a88b2fc7292278becf3d7b91852b"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "2e3da12b07b2c9777d4a031f0b95d6c9105fc2e78f92bd78994486dd2594bc64"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
hash = "0800671364602f858af55486d182ae32d03ef61e635dc685d01b53117c61cb8d"
metafile = true

[[files]]
file = "mods/anvians-lib.pw.toml"
hash = "2df32a935b70ed3e882fd90a3f9c537143174e053f44abb2a2ed4f1f8284f40b"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d2280c3618fef38838e835f44158f72e61bd2db03cb90842f6ecfdc1ab57b39"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2bcfa9dd8acca3e21de5d71dc5ff19bdd95bb400294117a6cc16a43530b13e16"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "067f90b00da0445f8630b77052f87e10c4dfaea1f1cf8aa5d8477696f7accee1"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "2144aa7ef7131eb4ce1b58927c0c716e3b89d0b151ce8484ee92788600df8917"
metafile = true

[[files]]
file = "mods/better-climbing.pw.toml"
hash = "858174fc979946f390029ecb7ec904f0d6372de58372a502107461e71756f7b9"
metafile = true

[[files]]
file = "mods/block-runner.pw.toml"
hash = "4147ac526363305adf3eb4d372f29fdb95cf369d16ee0ebe4cc5015196bbbfc1"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "6096cde0137dd79020a736ed8004b94ffe3cf6b090468e322afb071db7f4b5ec"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "10409d8a62cc71f8763e068c6774205d1620a2b9ac53985dfb44550d812251a9"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "66c12aea9b67e4722e9bebf17e77542f5ff8f85bbb0534c337ed0b293c9d5717"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6e97c6bdac0e568015294cf58f0a9fa43fb70042d252db9b578dd85a0a99137"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "dcca1c65343318559caa9988c9f602d56dd11177677a529730ec257b9fac673e"
metafile = true

[[files]]
file = "mods/coffdoublejump.pw.toml"
hash = "2254aaee4cacc321cdbb7af23f29313716cbe44d1d9769cc469172ff6e584807"
metafile = true

[[files]]
file = "mods/coffwallclimb.pw.toml"
hash = "e8aac4d75a08c13b132b3065044767133b5e226c73200c758bd19390cfdbd5be"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/comfortable-campfires.pw.toml"
hash = "094d588bc7391e105334991e1dcccb8ef7f60c10f8befa8755f14852df893af4"
metafile = true

[[files]]
file = "mods/compass-cleaner.pw.toml"
hash = "f81888b71f7c9164c9adde564275d6dade69079e65b5b48fd7ec2f4589190cba"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "e7c60c49c191e3b603eca7223adccaad6c63705d32c4899e1e358173cd25e748"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "9ac1c1cf7da5b0fbbd67a2491d99588cd14cb60e77a67b2c91b9533052244fb3"
metafile = true

[[files]]
file = "mods/crate-delight.pw.toml"
hash = "76b633af47cf5cbfd4121c978bf7813a4af05a638b69cfcb53dcc32edf2ac203"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "31c6bd88dfd57b004c6a483729bf9941b2c251ca0b805b58c6842810df5db3db"
metafile = true

[[files]]
file = "mods/crops-love-rain.pw.toml"
hash = "237a2dc34816516e8ddc4caf6583e74325bc095d36303aadecd8c2e2cef39029"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "0c591553cf99aef771688a7609d9fd17ee64579521c44dd063197b7aeb329ecd"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "ffbd09f86452c0cfec930625f5741c6c8f382d73a8210f6fc8d7fb74ef546738"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
hash = "66e8f55779695f4c0b9eaccb155f7ee100b49363706bad534f954b5c6aba28fa"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "f2df7f4675bf3d2a5c3113521c836c9df3c8933ce63e0b988c25c5d91b0b379d"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "f2a5c0bc5aa433e4d32809b9837909976b52c9a3d337b6512cd059c42bd67bde"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "d3c80654bb1fafc7d7439f78210d43e9e2dcd9904fbcdca0e162a35175d60eec"
metafile = true

[[files]]
file = "mods/enchantonce.pw.toml"
hash = "72e91e261274e8eb2b6ff40ddce23094c99725a79939a46596fd9cc39add175c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "51de4130932fdc96ff6c703f1d6fa2c0cfda04454d3e2ec5501220ac6eb6c133"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "44130a406ee7e6331adb1fc5dba46c7f6e126b46eaeba20b284dc7f7a96c478a"
metafile = true

[[files]]
file = "mods/fokusapi.pw.toml"
hash = "93faac8dd1a3b641923e1d99727970254ad8661df4a324e4a7ffdfe82da363ea"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "f9cf40980833dd562e31de3d2be96979c9fd752b5d5e16dcb314d5eb9e4f4d3d"
metafile = true

[[files]]
file = "mods/horse-expert.pw.toml"
hash = "4c1beb754d4a7ca9594defd8e0a4607422c1cbf9ac4ba829a208395e4f83ca60"
metafile = true

[[files]]
file = "mods/horseman.pw.toml"
hash = "6446cc378e7d503424b5045e875ad57cad6d0d78fe01ec0fca9b1de40bac6391"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6e800080e9bc8efb8f1a94a6e4ed3167a58b3d8f29a4ae7aba8cdde35c08d13e"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "bef0d78723bcf15335544a175244cb43416a58977e2b7551a7b5200a85af3bfa"
metafile = true

[[files]]
file = "mods/inventory-totem.pw.toml"
hash = "7878a5dd155ed5c36c025a74a74a899613524699d142cf84e6e0f746c0f0434b"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "29c6c7c86f300f2ae6ae04e81bf35b04ee01616387b89cb229f3a597883fa5fd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "2872f1fe9f477197ff81cdcd53ee2510e69da4e166bc4d2345bbd98fe83904a1"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7415133b01964dfef9ec69f1c943baad091fd8b81429317b10068e011d600fe2"
metafile = true

[[files]]
file = "mods/jakes-build-tools.pw.toml"
hash = "e79cfdbee998758cc97022365eb71d5255b3df2cd7dd922d094c81cf2d77fc4a"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "1a84f2a9750aef841fd839c305704069c7b82f0e3b2a697d4c5e226b4e5e6cc3"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "13e25ae905686f960b055236ae247b144262affeb627b123287cb39a959e7120"
metafile = true

[[files]]
file = "mods/jump-over-fences.pw.toml"
hash = "7e16d4d10c1f5482aa456918414d85a1394f3f80bd748685fc4213b1071d2171"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "cb4d4001e2d24404bd9eb5140e8fccffec77a906367a9e79c30305e986d4ccee"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "0c9fe9d3171b954072c666eb81c3c466419f4a06c5321786cd0ee5167145f54b"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e612afec52bf64afc5792d2c65a35434a1bc8f3ab985b043a41c0493a00bd532"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "52ae97859a86e9f624fd4890fb0852a0eb2b7485e1614b7b83e1d51b06d896d3"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e07224b54155142345279069bd370184580e7b33b8f414fa0ee110030569c66c"
metafile = true

[[files]]
file = "mods/mastercutter.pw.toml"
hash = "6085654180887fa259b64cbd202abd83180b6fcd1483f11f30dad39b9c774d51"
metafile = true

[[files]]
file = "mods/mavapi.pw.toml"
hash = "c3aadff6fc432784986c2661ba44c60a8ee6616d334f7f80127bcc48bdbacfc2"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
hash = "3c4f127cf9fe999a75b61d53bec70758f0633c9b50ab86699f164fab57f774f6"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "2b49d69a1d8edc92dbb197ebed7b2c9a30961bef4dac8649494b6e7d4b13d8e4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "642198a90b5483e38a71439e576ca0dc7f657774849404bfb2c310bf020f45e3"
metafile = true

[[files]]
file = "mods/moving-elevators.pw.toml"
hash = "22762525f12e2bd06852a1990c758a9e627dd3d47bfa18f7052f6e5efbcf4917"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "668913c24dfe97c1134eac98f9d60c2222171daef99c1698c59ea6b8ad3802f4"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "f379353bcb2018d8f77c2d4c45c31ec32506243210a581e364845fb88cbc3b51"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "8a881916883639f35b3938c2d462f948ef4b12e26852e8eaf95c262ab7da6fcf"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "708e00726602c4c53d8f0ae49eea1b2a0623ce4a301086067bab312fb787f9ec"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "ccd820352c2ba1f129a94276b1349b675feef99b9fb0e3397a41146118a0c7fd"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "f86f603155e3b9b8a2d48a63b115dfa8ccb4a7abf214a9c59d2d580e35f3818d"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "d369f884b004535c26a8c1f607572873c8c4b1d0712947d2c163e79e4d812959"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "117370be8637a805af8fc968a94cb76f15c69b921654b1eee58755ee63cd2bef"
metafile = true

[[files]]
file = "mods/realistic-bees.pw.toml"
hash = "77cf405c5086fa070ae533e26bd00b3683c9c9ddc6698494e7bf929b24491748"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1753d40819ec2706d443118d331f48acbe1f9c0ce577480bf0723e9b1c567e6e"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "f882fac723d7126084eeacfad1e83fb993d2277f0900b644bdb96b6306f72813"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "06acd35a0c6b3a5e7e9871bfb1cbc00cd83b4482bf4b523895f041acb2b103bc"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "dbfe1f73542f7a06112c9f8f5bfe2ab44e57eef5091a412394ade407662a82c5"
metafile = true

[[files]]
file = "mods/shulker-drops-two.pw.toml"
hash = "dca7fd0576fef97ce0afb58b4f8b15b12de61f3570a5e47c62b6bfffa4ba6038"
metafile = true

[[files]]
file = "mods/sodium-extra-information.pw.toml"
hash = "5b4dbdac99eb3321412b34dcb046e0a503863c2a79f9b22c77173c74467e1152"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1cb18ffacfb195efd1b9ec3ceea48a95095835322d89a4c7565cc1d1fdaa9390"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "527441f56f12bd48d63de82dc5acec0a371fcaf4d2b21ec6975019b4dc79a5d3"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "aafe3c856f52d86ee8c8b26594728151f3ebb26f4a9946014b978a21faf67013"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "3d8e6e588009190fbfd28006d7fcb4889bde08db4c5ea515dfd33b05cbb540a6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "a7600cdc549a2ecdb47169a03bed83064b42ba773dcb3d8e01a340ef4a0d2ff6"
metafile = true

[[files]]
file = "mods/stack-refill.pw.toml"
hash = "2b353bc499f08c16f8745bc07b8da39e68ba47d77416b4fe3a3abf6745e35aec"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "da1c3c1b7f5385b692cb6e771e467b64736a7d942c490fab1899e63d4a3eeec3"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1dca0aaaba95c8e279889a580f9d4f87eb4e59cf9ca98a82dbb707e802404339"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "2427f8970b137ae8fd15b4cf1f08e0879094d632da493be01e797b57ed9a6060"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "e199b66652d265a9df7f689026f3a9494d0809ebda36c066fe1119e1dcf210c2"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "ee4de268578f62d89243d138646b4fa5573d9c1418e5346a2767b548c7fca573"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
hash = "09a27bbb3ca422fb79498bd13555c2511cdc0fe8ced5160c001f15a1ecf3d278"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "6c95687fa623ac7ae76478c77b514491cd59aed8f36f76b9ac35cdda82c8cffc"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "5e87caea13a44193abf997de56cf3cab2eb9feb1d8be35e0203f06df3552b9c5"
metafile = true

[[files]]
file = "mods/universal-bone-meal.pw.toml"
hash = "bce0f2a5dc612ac123c2cf623cdda13e03c1f1a6d49fc2177f9c49398126ac5d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "5ddf85be8289aa440eaaf2e17547680ccb6cf55aacc0bd2df56e2a0991e51d0a"
metafile = true

[[files]]
file = "resourcepacks/cozy-beds.pw.toml"
hash = "dc16b5ddfe76903e674ffea09285e0ab6888c85f3c4aa87d8ae578af7c79b279"
metafile = true

[[files]]
file = "resourcepacks/cubic-sun-moon.pw.toml"
hash = "6d198fcead3ae516d33d9011f3ecf9717a72b963aadea7a6b3ad7f0c7cada070"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true

[[files]]
file = "shaderpacks/miniature-shader.pw.toml"
hash = "505c3abf34e1c48a1729e26db299ce1ef0777f7bbc88bc4302d9c66e42e95503"
metafile = true

[[files]]
file = "shaderpacks/solas-shader.pw.toml"
hash = "4b9fa848963dbf05b3e295ae91087adcd50e1fef6a92ad3af9b526c95d23cbb3"
metafile = true
