name = "Bry Pack"
author = "Bryan"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74de47cbea53d12d61a91dc9a77ffc02e9aeec94a4b4737e7559c1c3cb34d0aa"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
