name = "Bry Pack"
author = "Bryan"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "140e5cd71c50080f4b810ceb1435f327023a8557ab95fc514248033489d1462c"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
