name = "Bry Pack"
author = "Bryan"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "590c3738e73252b17f96a166b291f83a05dab1caeb92f1706540fd02d3775117"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
