name = "Bry Pack"
author = "Bryan"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fcd619b82cc96f5d18c0688cfaef4218dea991028d38c16f7915dd9cc14cea4"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
