name = "Bry Pack"
author = "Bryan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8661b0e9aa289b5184a0a07163d5a33e0cf0dd6c304cb2c32146cc43bdb15c7f"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
