name = "Bry Pack"
author = "Bryan"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cc8b13f6d8db992551741b0493b719b9c58f22c803ef2a599803a8381134bee"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
