name = "Bry Pack"
author = "Bryan"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c903f4182e74acd80763f0e24d825e5e9defa63a9f4a315720f61dab808cfb80"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.31-beta"
